default: &default
  store_options:
    max_age: <%= 7.days.to_i %>
    max_size: <%= 256.megabytes %>
    namespace: <%= Rails.env %>

development:
  <<: *default
  store_options:
    max_size: <%= 128.megabytes %>
    max_age: <%= 1.day.to_i %>

test:
  <<: *default
  store_options:
    max_size: <%= 64.megabytes %>
    max_age: <%= 1.hour.to_i %>

production:
  database: cache
  <<: *default
  store_options:
    max_size: <%= 256.megabytes %>
    max_age: <%= 30.days.to_i %>