require './db/seeds/admins'
# require './db/seeds/companies'
require './db/seeds/categories'
# require './db/seeds/products'
require './db/seeds/sitename'
require './db/seeds/privacy_policy'
require './db/seeds/terms_of_use_site'
require './db/seeds/contact'
require './db/seeds/about'
require './db/seeds/vacancy'
require './db/seeds/mechanics'
